@startuml

participant borrower as bw
participant lender as ld
entity "crowd lending platform" as cl
entity bank as bk

group account
bw -> cl: Create personal account
end group

group account
ld -> cl: Create personal account for each lender
end group

group loan request
bw -> cl: Request loan

note over bw, cl: borrower defines the community (target group of lender)

cl -> ld: notify loan request creation

note over ld, cl: only lenders within community receive a notification

group contribution
ld -> cl: contribute to loan request

group transfer
cl -> bk: verifies fund availability
bk -> cl: validates fund availability
note over cl: when loan request amount is matching total contributions

cl -> bk: request fund transfer
bk -> cl: validates fund transfer
end group

end group

cl -> bw: grant loan
end group

group loan
bw -> cl: pay back funds

group Transfer
cl -> bk: request fund transfer
bk -> cl: validates fund transfer
end group

cl -> ld: notify (partial) pay back
end group
@enduml