@startuml

allowMixing

skinparam nodesep 100
skinparam ranksep 100

skinparam ClassBackgroundColor<<TBD>> #lightgrey

class Account {
    owner
    ---
    observers: None
}

package lending {
    class LoanRequest {
        borrower
        lending community
        ---
        observers: None
    }

    class Loan {
        borrower
        lender
        ---
        observers: None
    }
}

package banking {
    class Transfer {
        banking system
        emitter
        recipient
        ---
        observers: None
    }

    class Contribution {
        banking system
        borrower
        lender
        ---
        observers: None
    }

    class BankingInterface {
        banking representative
        ---
        observers: anyone
    }
}

Account "1"-->"0..n" LoanRequest
Account "1"-->"0..n" Loan
LoanRequest "1"-l->"0..n" Loan
LoanRequest --> Contribution
Loan --> Transfer

@enduml
