version: "2.4"

volumes:
  keycloak-db: { }

services:

  api:
    build:
      context: api
    ports:
      - "8080:8080"
      - "8000:8000"
      - "8888:8888"
    environment:
      SYSTEM_USER: bankingsystem
      SYSTEM_PASSWORD: super-secret-system-security-safe
      KEYCLOAK_REALM: ${NC_APP_NAME}
      KEYCLOAK_CLIENT_ID: ${NC_APP_NAME}
      KEYCLOAK_URL: ${KEYCLOAK_URL:-http://keycloak:11000}
      ENGINE_URL: ${ENGINE_URL:-http://engine:12000}
      READ_MODEL_URL: ${READ_MODEL_URL:-http://read-model:15000}
      HTTP_PORT: 8080
      HTTP_ADMIN_PORT: 8000
      # JVM remote debug
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888
      ACCESS_LOG_VERBOSITY: "MAX"
      API_SERVER_URL: ${API_SERVER_URL:-http://localhost:8080}
      CORS_ALLOWED_ORIGINS: ${API_SERVER_URL:-http://localhost:8080},https://community.fluidapp.io
    healthcheck:
      test: "curl -s -f http://localhost:8000/health || exit 1"
      interval: 1s
      retries: 100
