@startuml
title System components & requirements

skinparam defaultFontName Bahnschrift
skinparam defaultFontColor #6d6e71
skinparam defaultFontSize 16
skinparam defaultTextAlignment left
skinparam titleFontSize 24
skinparam arrowFontStyle bold
skinparam SequenceGroupBackgroundColor #83414c
skinparam SequenceGroupBorderColor #83414c
skinparam SequenceGroupHeaderFontColor White
skinparam ArrowColor #00FF00
skinparam ArrowColor #83414c
skinparam ArrowThickness 3
skinparam LegendBackgroundColor #FFFFFF
skinparam LegendBorderThickness 0

rectangle "Banking System" {
    node "Cash availability service" as cas
}
rectangle "Decentralised lending platform\n(described system)" {
    node Account as a
    node "Loan Request" as lr
    node Loan as l
    node "Banking System Interface" as bsi
}

a --> l
a --> lr
a --> bsi
lr -> l
bsi --> cas

@enduml