@startuml

skinparam ranksep 100
skinparam ActorBackgroundColor<<Assignment>> #pink
skinparam ActorBorderColor<<Assignment>> #red
skinparam ActorBackgroundColor<<ScopedRole>> #lightgreen
skinparam ActorBorderColor<<ScopedRole>> #green

actor "Borrower" as borrower
actor "Lender" as lender
actor "Bank" as bank

package "Loan Request" {
    usecase "Create loan request" as create_loan_request
    usecase "Subscribe loan request" as subscribe_loan_request
    usecase "Cancel loan request subscription" as unsubscribe_loan_request
}

package "Loan" {
    usecase "Pay loan" as pay_loan
    usecase "Create loan" as create_loan
}

borrower -u-> create_loan_request
lender -u-> subscribe_loan_request
lender -u-> unsubscribe_loan_request
bank --> create_loan
borrower --> pay_loan


@enduml
